{
    "openapi": "3.1.0",
    "info": {
        "title": "Garage 61 API V1",
        "description": "Integration API for Garage 61",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://garage61.net/api/v1"
        }
    ],
    "paths": {
        "/car-groups": {
            "get": {
                "tags": [
                    "content"
                ],
                "summary": "Available car groups.",
                "description": "Car groups to which the user has access.\n\nThis is a personalized view and depends on the enabled platforms.\n\nFor simulator platforms such as iRacing, this returns all available\ncar groupss, not just the ones that are owned by the user.\n",
                "operationId": "findCarGroups"
            }
        },
        "/cars": {
            "get": {
                "tags": [
                    "content"
                ],
                "summary": "Available cars.",
                "description": "Cars to which the user has access.\n\nThis is a personalized view and depends on the enabled platforms.\n\nFor simulator platforms such as iRacing, this returns all available\ncars, not just the ones that are owned by the user.\n",
                "operationId": "findCars"
            }
        },
        "/laps": {
            "get": {
                "tags": [
                    "driving_data"
                ],
                "summary": "Find laps and lap records.",
                "description": "Search for laps or lap records.\n\nThis method takes a lot of parameters and allows you to find laps or\nlap records. To get a good idea at the kind of filtering you can do,\nread the [documentation on lap filtering](/docs/usage/filtering) first.\n\nYou will always need to supply at least a track, a car or a user.\n\nTo map the filtering capabilities of the app on the parameters below,\nhere's an overview on which parameters are used for each filter in the\napp:\n[...]",
                "operationId": "findLaps",
                "security": [
                    {
                        "oauth2": [
                            "driving_data"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/laps/{id}": {
            "get": {
                "tags": [
                    "driving_data"
                ],
                "summary": "Get information about a specific lap.",
                "description": "Returns all info about a specific lap.\n\n## Limitations\n\nThis method only returns laps driven yourself or your team mates.\n\nData returned adheres to the defined privacy settings and is thus\nspecific to the user linked to the API token.\n",
                "operationId": "getLap",
                "security": [
                    {
                        "oauth2": [
                            "driving_data"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/laps/{id}/csv": {
            "get": {
                "tags": [
                    "driving_data"
                ],
                "summary": "Export the telemetry for a lap as a CSV file.",
                "description": "Returns a CSV file with the telemetry for the requested lap (if available).\n\n## Limitations\n\nThis method only returns laps driven yourself or your team mates.\n\nData returned adheres to the defined privacy settings and is thus\nspecific to the user linked to the API token.\n",
                "operationId": "getLapCSV",
                "security": [
                    {
                        "oauth2": [
                            "driving_data"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "general"
                ],
                "summary": "Information about the currently authenticated user.",
                "description": "Returns information about the currently authenticated user.\n",
                "operationId": "me"
            }
        },
        "/me/accounts": {
            "get": {
                "tags": [
                    "general"
                ],
                "summary": "Get linked accounts for the current user.",
                "description": "Linked accounts such as the iRacing account.\n\nReturns the driver ratings for each attached account, optionally\nwith their history.\n",
                "operationId": "getAccounts"
            }
        },
        "/me/datapackgroups": {
            "post": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Subscribe user to a data pack group.",
                "description": "Subscribes a user to the given data pack group.",
                "operationId": "createUserDataPackGroup",
                "security": [
                    {
                        "oauth2": [
                            "datapacks_subscriptions"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/me/datapackgroups/{id}": {
            "delete": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Unsubscribe user from a data pack group.",
                "description": "Unsubscribes a user from the given data pack group.",
                "operationId": "deleteUserDataPackGroup",
                "security": [
                    {
                        "oauth2": [
                            "datapacks_subscriptions"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/me/datapacks": {
            "post": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Subscribe user to a data pack.",
                "description": "Subscribes a user to the given data pack.",
                "operationId": "createUserDataPack",
                "security": [
                    {
                        "oauth2": [
                            "datapacks_subscriptions"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/me/datapacks/{id}": {
            "delete": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Unsubscribe user from a data pack.",
                "description": "Unsubscribes a user from the given data pack.",
                "operationId": "deleteUserDataPack",
                "security": [
                    {
                        "oauth2": [
                            "datapacks_subscriptions"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/me/statistics": {
            "get": {
                "tags": [
                    "general"
                ],
                "summary": "Get personal driving statistics.",
                "description": "Driving statistics for the authenticated user.\n\nEach returned record is a combination of car, track and day.\nYou'll need to sum up these rows according to the specific numbers you\nwant to calculate (e.g. per car).\n",
                "operationId": "getStatistics"
            }
        },
        "/platforms": {
            "get": {
                "tags": [
                    "content"
                ],
                "summary": "Available platforms.",
                "description": "All data is linked to a platform, which can either be a simulator\nplatform (such as [iRacing](https://www.iracing.com/)) or the real\nworld (identified by `-`).\n\nOnly platforms to which the user has access are returned.\n",
                "operationId": "findPlatforms"
            }
        },
        "/teams": {
            "get": {
                "tags": [
                    "teams"
                ],
                "summary": "Joined teams.",
                "description": "Teams that the authenticated user is part of.\n",
                "operationId": "findTeams"
            }
        },
        "/teams/{id}": {
            "get": {
                "tags": [
                    "teams"
                ],
                "summary": "Get information about a specific team.",
                "description": "Returns information about a team.\n\n## Limitations\n\nThis method only returns information about teams that the authenticated\nuser is a member of.\n\nThe member list of a team might not be included if the authenticated\nuser is not a team owner and the team is configured to only show the\nmember list to team owners.\n",
                "operationId": "getTeam"
            }
        },
        "/teams/{team}/datapackgroups": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Get data pack groups for a team.",
                "description": "Gets a list of the data pack groups defined for a team.\n",
                "operationId": "getTeamDataPackGroups",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapackgroups/{id}": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Get data pack group for a team.",
                "description": "Gets a single data pack group.\n\nDoes not include archived data packs, unless the app also has the `team_datapacks_archived_read` permission.\n",
                "operationId": "getTeamDataPackGroup",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapackgroups/{id}/members": {
            "post": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Add data pack to a data pack group.",
                "description": "Adds a data pack to the given data pack group.",
                "operationId": "createDataPackGroupMember",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_write"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapackgroups/{id}/members/{member}": {
            "delete": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Remove data pack from a data pack group.",
                "description": "Removes a data pack from the given data pack group.",
                "operationId": "deleteDataPackGroupMember",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_write"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapacks": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Get data packs for a team.",
                "description": "Gets a list of the data packs defined for a team.\n\nDoes not include archived data packs, unless the app also has the `team_datapacks_archived_read` permission.\n",
                "operationId": "getTeamDataPacks",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapacks/{id}": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Get data pack for a team.",
                "description": "Gets a single data pack.",
                "operationId": "getTeamDataPack",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Update data pack for a team.",
                "description": "Update a data packs.\n",
                "operationId": "updateTeamDataPack",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read",
                            "team_datapacks_write"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapacks/{id}/content/{item}/ghost.bin": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Download ghost lap file for a content item.",
                "description": "Downloads the ghost file (if available).\n\nOnly applicable to content items with `type == \"ghost_lap\"` or `type == \"lap\"`.\n\nFor content items with `type == \"lap\"`, you'll need to have telemetry\nviewing permissions to be able to load the ghost lap. See the\n`canViewTelemetry` field on `Lap`. Also pay attention to the\n`ghostAvailable` field: not every lap has a ghost file available for\ndownload.\n",
                "operationId": "getTeamDataPackContentGhostLapBin",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapacks/{id}/content/{item}/lap.csv": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Export telemetry for a lap content item.",
                "description": "Returns a CSV file with the telemetry for the requested lap (if available).\n\nOnly applicable to content items with `type == \"lap\"`.\n",
                "operationId": "getTeamDataPackContentLapCsv",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapacks/{id}/content/{item}/replay.bin": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Download file for a replay content item.",
                "description": "Downloads the replay file (if available).\n\nOnly applicable to content items with `type == \"replay\"`.\n",
                "operationId": "getTeamDataPackContentReplayBin",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/datapacks/{id}/content/{item}/setup.sto": {
            "get": {
                "tags": [
                    "data_packs"
                ],
                "summary": "Download iRacing setup for a setup content item.",
                "description": "Downloads the iRacing setup file (if available).\n\nOnly applicable to content items with `type == \"setup\"`.\n",
                "operationId": "getTeamDataPackContentSetupSto",
                "security": [
                    {
                        "oauth2": [
                            "team_datapacks_read"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/invites": {
            "post": {
                "tags": [
                    "teams"
                ],
                "summary": "Create team invite",
                "description": "Create an invite to join a team.",
                "operationId": "createTeamInvite",
                "security": [
                    {
                        "oauth2": [
                            "team_members"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/members/{id}": {
            "delete": {
                "tags": [
                    "teams"
                ],
                "summary": "Remove member from team",
                "description": "Removes a member from the team\n",
                "operationId": "deleteTeamMember",
                "security": [
                    {
                        "oauth2": [
                            "team_members"
                        ]
                    },
                    {
                        "personalAccessToken": []
                    }
                ]
            }
        },
        "/teams/{team}/statistics": {
            "get": {
                "tags": [
                    "teams"
                ],
                "summary": "Get team driving statistics.",
                "description": "Driving statistics for the members of the team.\n\nEach returned record is a combination of car, track, day and driver.\nYou'll need to sum up these rows according to the specific numbers you\nwant to calculate (e.g. per car).\n\n## Limitations\n\nThis method only returns information about teams that the authenticated\nuser is a member of.\n\nThe authenticated user will need to be a team owner if the team is\nconfigured to only show statistics to team owners.\n",
                "operationId": "getTeamStatistics"
            }
        },
        "/tracks": {
            "get": {
                "tags": [
                    "content"
                ],
                "summary": "Available tracks.",
                "description": "Tracks to which the user has access.\n\nThis is a personalized view and depends on the enabled platforms.\n\nFor simulator platforms such as iRacing, this returns all available\ntracks, not just the ones that are owned by the user.\n",
                "operationId": "findTracks"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://garage61.net/app/account/oauth",
                        "tokenUrl": "https://garage61.net/api/oauth/token",
                        "scopes": {
                            "datapacks_subscriptions": "Manage user data pack subscriptions",
                            "driving_data": "Access to driving data (personal and teammates)",
                            "team_datapacks_archived_read": "Read archived team data packs",
                            "team_datapacks_read": "Read team data packs",
                            "team_datapacks_subscribers_read": "Read data pack subscribers",
                            "team_datapacks_write": "Write team data packs",
                            "team_members": "Manage team members"
                        }
                    }
                }
            },
            "personalAccessToken": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [
        {
            "oauth2": []
        },
        {
            "personalAccessToken": []
        }
    ],
    "tags": [
        {
            "name": "general",
            "description": "General information"
        },
        {
            "name": "content",
            "description": "Content"
        },
        {
            "name": "driving_data",
            "description": "Driving data"
        },
        {
            "name": "teams",
            "description": "Teams"
        },
        {
            "name": "data_packs",
            "description": "Data packs"
        }
    ]
}